scrape_configs:
  - job_name: 'Spring WebFlux API'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['10.5.0.2:8081']
        labels:
          application: 'webfluxapi'